CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_INDICATOR=y
CONFIG_ZMK_BOOTLOADER_LED_INDICATOR=y
CONFIG_ZMK_BOOTLOADER_LED_TIMEOUT_MS=50
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_ZMK_SLEEP=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Reduce split key event drops/dupes on fast typing bursts (default 10)
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_POSITION_QUEUE_SIZE=20
